version: '3.8'

services:
  app:
    build: .
    container_name: whatbeatsrock-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/whatsbeatsrock
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VITE_API_URL=http://localhost:3000/api
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    container_name: whatbeatsrock-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=whatsbeatsrock
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: whatbeatsrock-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: